tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/cask-fonts"
tap "heroku/brew"
tap "ethereum/ethereum"

#Installing casks
cask 'warp'
cask 'visual-studio-code'
cask 'zoom'
cask 'discord'
cask 'font-fira-code'
cask 'flutter'
cask 'google-chrome'
cask 'vlc'
cask 'notion'
cask 'flutter'
cask 'whatsapp'
cask 'bitwarden'
cask 'obs'
cask 'transmission'
cask 'rectangle'
cask 'flycut'
cask 'keka'
cask 'devdocs'
cask 'yt-music'
cask 'visualboyadvance-m'
cask 'kap'
cask 'microsoft-word'
cask 'microsoft-powerpoint'
cask 'alloy'

#Installing Software
brew 'python3'
brew 'node@16'
brew 'yarn'
brew 'thefuck'
brew 'docker'
brew 'docker-machine'
brew 'kubectl'
brew 'bat'
brew 'nvm'
brew 'zsh'
brew 'tmux'
brew 'golang' 
brew 'httpd'
brew 'maven'
brew 'java11'
brew 'minikube'
brew 'hyperkit'
brew 'transmission-cli'
brew 'heroku'
brew 'ethereum'
brew 'neovim'
