tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/cask-fonts"

#Installing casks
cask 'iterm2'
cask 'visual-studio-code'
cask 'zoom'
cask 'discord'
cask 'font-fira-code'
cask 'flutter'
cask 'postman'
cask 'notion'

#Installing Software
brew 'python3'
brew 'node'
brew 'yarn'
brew 'thefuck'
brew 'docker'
brew 'docker-machine'
brew 'kubectl'
brew 'bat'
brew 'nvm'
brew 'zsh'
brew 'tmux'
brew 'golang' 
brew 'httpd'
brew 'maven'
brew 'java11'
brew 'minikube'
brew 'hyperkit'