#!/bin/bash
set -e
# Using the zsh installed by Homebrew
sudo dscl . -create /Users/$USER UserShell $(brew --prefix)/bin/zsh

git --version 2>&1 >/dev/null
GIT_IS_AVAILABLE=$?
if [ $GIT_IS_AVAILABLE -ne 0 ]; then
    echo "Git is not available"
    exit 1
fi

# Set up onetime links for all of the files
DOTFILES_REPO_PATH="$HOME/dotfiles"
if [ ! -d "$DOTFILES_REPO_PATH" ]; then
    echo "dotfiles don't exist at $DOTFILES_REPO_PATH"
    exit 1
fi

# Link time
ln -sf "$DOTFILES_REPO_PATH/Brewfile" ~/.Brewfile
ln -sf "$DOTFILES_REPO_PATH/zsh/.zshrc" ~/.zshrc
ln -sf "$DOTFILES_REPO_PATH/zsh/oh-my-zsh" ~/.oh-my-zsh
ln -sf "$DOTFILES_REPO_PATH/tmux" ~/.tmux
ln -sf "$DOTFILES_REPO_PATH/tmux/tmux.conf" ~/.tmux.conf

if [ ! -d "$HOME/.config" ]; then
   mkdir "$HOME/config"
fi

ln -sf "$DOTFILES_REPO_PATH/nvim" ~/.config/nvim
ln -sf "$DOTFILES_REPO_PATH/wezterm" ~/.config/wezterm
ln -sf "$DOTFILES_REPO_PATH/gitconfig/gitconfig" ~/.gitconfig

if [ ! -d "$HOME/.ssh" ]; then
   mkdir "$HOME/ssh"
fi
cp "$DOTFILES_REPO_PATH/ssh/config" ~/.ssh
cp "$DOTFILES_REPO_PATH/ssh/id_ed25519" ~/.ssh
cp "$DOTFILES_REPO_PATH/ssh/id_ed25519.pub" ~/.ssh

brew bundle -v

ansible-vault decrypt ~/.ssh/id_ed25519

## Clone tpm
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm


## Key repeating
defaults write -g InitialKeyRepeat -int 15 # normal minimum is 15 (225 ms)
defaults write -g KeyRepeat -int 2 # normal minimum is 2 (30 ms)
