#!/bin/bash
set -e

git --version 2>&1 >/dev/null
GIT_IS_AVAILABLE=$?
if [ $GIT_IS_AVAILABLE -ne 0 ]; then
    echo "Git is not available"
    exit 1
fi

# Set up onetime links for all of the files
DOTFILES_REPO_PATH="$HOME/dotfiles"
if [ ! -d "$DOTFILES_REPO_PATH" ]; then
    echo "dotfiles don't exist at $DOTFILES_REPO_PATH"
    exit 1
fi

# Install the required dependencies
brew install git
brew install stow
brew install zsh

# Using the zsh installed by Homebrew
sudo dscl . -create /Users/$USER UserShell $(brew --prefix)/bin/zsh

if [ ! -d "$HOME/.ssh" ]; then
   mkdir "$HOME/ssh"
fi
cp "$DOTFILES_REPO_PATH/ssh/config" "$HOME/.ssh"
cp "$DOTFILES_REPO_PATH/ssh/id_ed25519" "$HOME/.ssh"
cp "$DOTFILES_REPO_PATH/ssh/id_ed25519.pub" "$HOME/.ssh"

if [ ! -d "$HOME/.config/spotifyd" ]; then
   mkdir "$HOME/.config/spotifyd"
fi
cp "$DOTFILES_REPO_PATH/spotifyd/spotifyd.conf" "$HOME/.config/spotifyd/spotifyd.conf"

brew bundle -v

ansible-vault decrypt "$HOME/.ssh/id_ed25519"
ansible-vault decrypt "$HOME/.config/spotifyd/spotifyd.conf"

## Clone tpm
if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
   git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
fi

## Key repeating
defaults write -g InitialKeyRepeat -int 15 # normal minimum is 15 (225 ms)
defaults write -g KeyRepeat -int 2 # normal minimum is 2 (30 ms)
git remote set-url origin git@github.com:saphal1998/dotfiles.git
