#!/bin/bash
set -e
# Using the zsh installed by Homebrew
sudo dscl . -create /Users/$USER UserShell $(brew --prefix)/bin/zsh

git --version 2>&1 >/dev/null
GIT_IS_AVAILABLE=$?
if [ $GIT_IS_AVAILABLE -ne 0 ]; then
    echo "Git is not available"
    exit 1
fi

# Set up onetime links for all of the files
DOTFILES_REPO_PATH="~/dotfiles"
if [ ! -d "$DOTFILES_REPO_PATH" ]; then
    echo "dotfiles don't exist at $DOTFILES_REPO_PATH"
    exit 1
fi

# Link time
ln -sf "$DOTFILES_REPO_PATH/Brewfile" ~/.Brewfile
ln -sf "$DOTFILES_REPO_PATH/zsh/.zshrc" ~/.zshrc
ln -sf "$DOTFILES_REPO_PATH/tmux/tmux.conf" ~/.tmux.conf
ln -sf "$DOTFILES_REPO_PATH/nvim" ~/.config/nvim
ln -sf "$DOTFILES_REPO_PATH/alacritty" ~/.config/alacritty
ln -sf "$DOTFILES_REPO_PATH/kitty" ~/.config/kitty
ln -sf "$DOTFILES_REPO_PATH/yabai" ~/.config/yabai
ln -sf "$DOTFILES_REPO_PATH/skhd" ~/.config/skhd
ln -sf "$DOTFILES_REPO_PATH/gitconfig/gitconfig" ~/.gitconfig
