-- return {
--   "nvimtools/none-ls.nvim",
--   dependencies = { 'nvim-lua/plenary.nvim' },
--   config = function()
--     local null_ls = require("null-ls")
--
--     null_ls.setup({
--       sources = {
--         null_ls.builtins.code_actions.eslint_d,
--         null_ls.builtins.formatting.prettierd,
--         null_ls.builtins.formatting.clang_format,
--         null_ls.builtins.formatting.black,
--       },
--       filetypes = { java = false }
--     })
--   end
-- }
