#!/usr/bin/env bash

FILE="CMakeLists.txt"
if [ ! -f "$FILE" ]; then
    echo "$FILE does not exist."
fi

mkdir -p build/
cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_EXPORT_COMPILE_COMMANDS=1
make -C build -d
