#!/usr/bin/env bash

processID=$1

if [[ -z $processID ]]
then
    echo "You need a process ID to check the memory usage"
    exit 1
fi

while true
do
    memoryUsage=$(ps -p $processID -o rss=)
    if [ -n "$memoryUsage" ]
    then
        memoryUsageMB=$(echo "scale=2; $memoryUsage / 1024" | bc)
        echo "Memory usage: $memoryUsageMB MB"
    else
        echo "Process with ID $processID not found."
        exit 1
    fi
    sleep 1
done

